<?php declare(strict_types = 1);

namespace SlevomatCsobGateway;

use function array_search;

enum Country: string
{

	case AFG = 'AF';
	case ALA = 'AX';
	case ALB = 'AL';
	case DZA = 'DZ';
	case ASM = 'AS';
	case AND = 'AD';
	case AGO = 'AO';
	case AIA = 'AI';
	case ATA = 'AQ';
	case ATG = 'AG';
	case ARG = 'AR';
	case ARM = 'AM';
	case ABW = 'AW';
	case AUS = 'AU';
	case AUT = 'AT';
	case AZE = 'AZ';
	case BHS = 'BS';
	case BHR = 'BH';
	case BGD = 'BD';
	case BRB = 'BB';
	case BLR = 'BY';
	case BEL = 'BE';
	case BLZ = 'BZ';
	case BEN = 'BJ';
	case BMU = 'BM';
	case BTN = 'BT';
	case BOL = 'BO';
	case BIH = 'BA';
	case BES = 'BQ';
	case BWA = 'BW';
	case BVT = 'BV';
	case BRA = 'BR';
	case IOT = 'IO';
	case BRN = 'BN';
	case BGR = 'BG';
	case BFA = 'BF';
	case BDI = 'BI';
	case KHM = 'KH';
	case CMR = 'CM';
	case CAN = 'CA';
	case CPV = 'CV';
	case CYM = 'KY';
	case CAF = 'CF';
	case TCD = 'TD';
	case CHL = 'CL';
	case CHN = 'CN';
	case CXR = 'CX';
	case CCK = 'CC';
	case COL = 'CO';
	case COM = 'KM';
	case COG = 'CG';
	case COK = 'CK';
	case CRI = 'CR';
	case CIV = 'CI';
	case HRV = 'HR';
	case CUB = 'CU';
	case CUW = 'CW';
	case CYP = 'CY';
	case CZE = 'CZ';
	case COD = 'CD';
	case DNK = 'DK';
	case DJI = 'DJ';
	case DMA = 'DM';
	case DOM = 'DO';
	case ECU = 'EC';
	case EGY = 'EG';
	case SLV = 'SV';
	case GNQ = 'GQ';
	case ERI = 'ER';
	case EST = 'EE';
	case ETH = 'ET';
	case FLK = 'FK';
	case FRO = 'FO';
	case FJI = 'FJ';
	case FIN = 'FI';
	case FRA = 'FR';
	case GUF = 'GF';
	case PYF = 'PF';
	case ATF = 'TF';
	case GAB = 'GA';
	case GMB = 'GM';
	case GEO = 'GE';
	case DEU = 'DE';
	case GHA = 'GH';
	case GIB = 'GI';
	case GRC = 'GR';
	case GRL = 'GL';
	case GRD = 'GD';
	case GLP = 'GP';
	case GUM = 'GU';
	case GTM = 'GT';
	case GGY = 'GG';
	case GIN = 'GN';
	case GNB = 'GW';
	case GUY = 'GY';
	case HTI = 'HT';
	case HMD = 'HM';
	case HND = 'HN';
	case HKG = 'HK';
	case HUN = 'HU';
	case ISL = 'IS';
	case IND = 'IN';
	case IDN = 'ID';
	case IRQ = 'IQ';
	case IRL = 'IE';
	case IRN = 'IR';
	case IMN = 'IM';
	case ISR = 'IL';
	case ITA = 'IT';
	case JAM = 'JM';
	case JPN = 'JP';
	case JEY = 'JE';
	case JOR = 'JO';
	case KAZ = 'KZ';
	case KEN = 'KE';
	case KIR = 'KI';
	case XKX = 'XK';
	case KWT = 'KW';
	case KGZ = 'KG';
	case LAO = 'LA';
	case LVA = 'LV';
	case LBN = 'LB';
	case LSO = 'LS';
	case LBR = 'LR';
	case LBY = 'LY';
	case LIE = 'LI';
	case LTU = 'LT';
	case LUX = 'LU';
	case MAC = 'MO';
	case MKD = 'MK';
	case MDG = 'MG';
	case MWI = 'MW';
	case MYS = 'MY';
	case MDV = 'MV';
	case MLI = 'ML';
	case MLT = 'MT';
	case MHL = 'MH';
	case MTQ = 'MQ';
	case MRT = 'MR';
	case MUS = 'MU';
	case MYT = 'YT';
	case MEX = 'MX';
	case FSM = 'FM';
	case MDA = 'MD';
	case MCO = 'MC';
	case MNG = 'MN';
	case MNE = 'ME';
	case MSR = 'MS';
	case MAR = 'MA';
	case MOZ = 'MZ';
	case MMR = 'MM';
	case NAM = 'NA';
	case NRU = 'NR';
	case NPL = 'NP';
	case NLD = 'NL';
	case NCL = 'NC';
	case NZL = 'NZ';
	case NIC = 'NI';
	case NER = 'NE';
	case NGA = 'NG';
	case NIU = 'NU';
	case NFK = 'NF';
	case MNP = 'MP';
	case PRK = 'KP';
	case NOR = 'NO';
	case OMN = 'OM';
	case PAK = 'PK';
	case PLW = 'PW';
	case PSE = 'PS';
	case PAN = 'PA';
	case PNG = 'PG';
	case PRY = 'PY';
	case PER = 'PE';
	case PHL = 'PH';
	case PCN = 'PN';
	case POL = 'PL';
	case PRT = 'PT';
	case PRI = 'PR';
	case QAT = 'QA';
	case REU = 'RE';
	case ROU = 'RO';
	case RUS = 'RU';
	case RWA = 'RW';
	case SHN = 'SH';
	case KNA = 'KN';
	case LCA = 'LC';
	case SXM = 'SX';
	case MAF = 'MF';
	case SPM = 'PM';
	case VCT = 'VC';
	case WSM = 'WS';
	case SMR = 'SM';
	case STP = 'ST';
	case SAU = 'SA';
	case SEN = 'SN';
	case SRB = 'RS';
	case SYC = 'SC';
	case SLE = 'SL';
	case SGP = 'SG';
	case SVK = 'SK';
	case SVN = 'SI';
	case SLB = 'SB';
	case SOM = 'SO';
	case ZAF = 'ZA';
	case SGS = 'GS';
	case KOR = 'KR';
	case SSU = 'SS';
	case ESP = 'ES';
	case LKA = 'LK';
	case SDN = 'SD';
	case SUR = 'SR';
	case SJM = 'SJ';
	case SWZ = 'SZ';
	case SWE = 'SE';
	case CHE = 'CH';
	case SYR = 'SY';
	case TWN = 'TW';
	case TJK = 'TJ';
	case TZA = 'TZ';
	case THA = 'TH';
	case TLS = 'TL';
	case TGO = 'TG';
	case TKL = 'TK';
	case TON = 'TO';
	case TTO = 'TT';
	case TUN = 'TN';
	case TUR = 'TR';
	case TKM = 'TM';
	case TCA = 'TC';
	case TUV = 'TV';
	case UGA = 'UG';
	case UKR = 'UA';
	case ARE = 'AE';
	case GBR = 'GB';
	case USA = 'US';
	case UMI = 'UM';
	case URY = 'UY';
	case UZB = 'UZ';
	case VUT = 'VU';
	case VAT = 'VA';
	case VEN = 'VE';
	case VNM = 'VN';
	case VGB = 'VG';
	case VIR = 'VI';
	case WLF = 'WF';
	case ESH = 'EH';
	case YEM = 'YE';
	case ZMB = 'ZM';
	case ZWE = 'ZW';

	private const LONG_CODES = [
		'AFG' => self::AFG,
		'ALA' => self::ALA,
		'ALB' => self::ALB,
		'DZA' => self::DZA,
		'ASM' => self::ASM,
		'AND' => self::AND,
		'AGO' => self::AGO,
		'AIA' => self::AIA,
		'ATA' => self::ATA,
		'ATG' => self::ATG,
		'ARG' => self::ARG,
		'ARM' => self::ARM,
		'ABW' => self::ABW,
		'AUS' => self::AUS,
		'AUT' => self::AUT,
		'AZE' => self::AZE,
		'BHS' => self::BHS,
		'BHR' => self::BHR,
		'BGD' => self::BGD,
		'BRB' => self::BRB,
		'BLR' => self::BLR,
		'BEL' => self::BEL,
		'BLZ' => self::BLZ,
		'BEN' => self::BEN,
		'BMU' => self::BMU,
		'BTN' => self::BTN,
		'BOL' => self::BOL,
		'BIH' => self::BIH,
		'BES' => self::BES,
		'BWA' => self::BWA,
		'BVT' => self::BVT,
		'BRA' => self::BRA,
		'IOT' => self::IOT,
		'BRN' => self::BRN,
		'BGR' => self::BGR,
		'BFA' => self::BFA,
		'BDI' => self::BDI,
		'KHM' => self::KHM,
		'CMR' => self::CMR,
		'CAN' => self::CAN,
		'CPV' => self::CPV,
		'CYM' => self::CYM,
		'CAF' => self::CAF,
		'TCD' => self::TCD,
		'CHL' => self::CHL,
		'CHN' => self::CHN,
		'CXR' => self::CXR,
		'CCK' => self::CCK,
		'COL' => self::COL,
		'COM' => self::COM,
		'COG' => self::COG,
		'COK' => self::COK,
		'CRI' => self::CRI,
		'CIV' => self::CIV,
		'HRV' => self::HRV,
		'CUB' => self::CUB,
		'CUW' => self::CUW,
		'CYP' => self::CYP,
		'CZE' => self::CZE,
		'COD' => self::COD,
		'DNK' => self::DNK,
		'DJI' => self::DJI,
		'DMA' => self::DMA,
		'DOM' => self::DOM,
		'ECU' => self::ECU,
		'EGY' => self::EGY,
		'SLV' => self::SLV,
		'GNQ' => self::GNQ,
		'ERI' => self::ERI,
		'EST' => self::EST,
		'ETH' => self::ETH,
		'FLK' => self::FLK,
		'FRO' => self::FRO,
		'FJI' => self::FJI,
		'FIN' => self::FIN,
		'FRA' => self::FRA,
		'GUF' => self::GUF,
		'PYF' => self::PYF,
		'ATF' => self::ATF,
		'GAB' => self::GAB,
		'GMB' => self::GMB,
		'GEO' => self::GEO,
		'DEU' => self::DEU,
		'GHA' => self::GHA,
		'GIB' => self::GIB,
		'GRC' => self::GRC,
		'GRL' => self::GRL,
		'GRD' => self::GRD,
		'GLP' => self::GLP,
		'GUM' => self::GUM,
		'GTM' => self::GTM,
		'GGY' => self::GGY,
		'GIN' => self::GIN,
		'GNB' => self::GNB,
		'GUY' => self::GUY,
		'HTI' => self::HTI,
		'HMD' => self::HMD,
		'HND' => self::HND,
		'HKG' => self::HKG,
		'HUN' => self::HUN,
		'ISL' => self::ISL,
		'IND' => self::IND,
		'IDN' => self::IDN,
		'IRQ' => self::IRQ,
		'IRL' => self::IRL,
		'IRN' => self::IRN,
		'IMN' => self::IMN,
		'ISR' => self::ISR,
		'ITA' => self::ITA,
		'JAM' => self::JAM,
		'JPN' => self::JPN,
		'JEY' => self::JEY,
		'JOR' => self::JOR,
		'KAZ' => self::KAZ,
		'KEN' => self::KEN,
		'KIR' => self::KIR,
		'XKX' => self::XKX,
		'KWT' => self::KWT,
		'KGZ' => self::KGZ,
		'LAO' => self::LAO,
		'LVA' => self::LVA,
		'LBN' => self::LBN,
		'LSO' => self::LSO,
		'LBR' => self::LBR,
		'LBY' => self::LBY,
		'LIE' => self::LIE,
		'LTU' => self::LTU,
		'LUX' => self::LUX,
		'MAC' => self::MAC,
		'MKD' => self::MKD,
		'MDG' => self::MDG,
		'MWI' => self::MWI,
		'MYS' => self::MYS,
		'MDV' => self::MDV,
		'MLI' => self::MLI,
		'MLT' => self::MLT,
		'MHL' => self::MHL,
		'MTQ' => self::MTQ,
		'MRT' => self::MRT,
		'MUS' => self::MUS,
		'MYT' => self::MYT,
		'MEX' => self::MEX,
		'FSM' => self::FSM,
		'MDA' => self::MDA,
		'MCO' => self::MCO,
		'MNG' => self::MNG,
		'MNE' => self::MNE,
		'MSR' => self::MSR,
		'MAR' => self::MAR,
		'MOZ' => self::MOZ,
		'MMR' => self::MMR,
		'NAM' => self::NAM,
		'NRU' => self::NRU,
		'NPL' => self::NPL,
		'NLD' => self::NLD,
		'NCL' => self::NCL,
		'NZL' => self::NZL,
		'NIC' => self::NIC,
		'NER' => self::NER,
		'NGA' => self::NGA,
		'NIU' => self::NIU,
		'NFK' => self::NFK,
		'MNP' => self::MNP,
		'PRK' => self::PRK,
		'NOR' => self::NOR,
		'OMN' => self::OMN,
		'PAK' => self::PAK,
		'PLW' => self::PLW,
		'PSE' => self::PSE,
		'PAN' => self::PAN,
		'PNG' => self::PNG,
		'PRY' => self::PRY,
		'PER' => self::PER,
		'PHL' => self::PHL,
		'PCN' => self::PCN,
		'POL' => self::POL,
		'PRT' => self::PRT,
		'PRI' => self::PRI,
		'QAT' => self::QAT,
		'REU' => self::REU,
		'ROU' => self::ROU,
		'RUS' => self::RUS,
		'RWA' => self::RWA,
		'SHN' => self::SHN,
		'KNA' => self::KNA,
		'LCA' => self::LCA,
		'SXM' => self::SXM,
		'MAF' => self::MAF,
		'SPM' => self::SPM,
		'VCT' => self::VCT,
		'WSM' => self::WSM,
		'SMR' => self::SMR,
		'STP' => self::STP,
		'SAU' => self::SAU,
		'SEN' => self::SEN,
		'SRB' => self::SRB,
		'SYC' => self::SYC,
		'SLE' => self::SLE,
		'SGP' => self::SGP,
		'SVK' => self::SVK,
		'SVN' => self::SVN,
		'SLB' => self::SLB,
		'SOM' => self::SOM,
		'ZAF' => self::ZAF,
		'SGS' => self::SGS,
		'KOR' => self::KOR,
		'SSU' => self::SSU,
		'ESP' => self::ESP,
		'LKA' => self::LKA,
		'SDN' => self::SDN,
		'SUR' => self::SUR,
		'SJM' => self::SJM,
		'SWZ' => self::SWZ,
		'SWE' => self::SWE,
		'CHE' => self::CHE,
		'SYR' => self::SYR,
		'TWN' => self::TWN,
		'TJK' => self::TJK,
		'TZA' => self::TZA,
		'THA' => self::THA,
		'TLS' => self::TLS,
		'TGO' => self::TGO,
		'TKL' => self::TKL,
		'TON' => self::TON,
		'TTO' => self::TTO,
		'TUN' => self::TUN,
		'TUR' => self::TUR,
		'TKM' => self::TKM,
		'TCA' => self::TCA,
		'TUV' => self::TUV,
		'UGA' => self::UGA,
		'UKR' => self::UKR,
		'ARE' => self::ARE,
		'GBR' => self::GBR,
		'USA' => self::USA,
		'UMI' => self::UMI,
		'URY' => self::URY,
		'UZB' => self::UZB,
		'VUT' => self::VUT,
		'VAT' => self::VAT,
		'VEN' => self::VEN,
		'VNM' => self::VNM,
		'VGB' => self::VGB,
		'VIR' => self::VIR,
		'WLF' => self::WLF,
		'ESH' => self::ESH,
		'YEM' => self::YEM,
		'ZMB' => self::ZMB,
		'ZWE' => self::ZWE,
	];

	public function getLongCode(): string
	{
		/** @var string */
		return array_search($this, self::LONG_CODES, true);
	}

}
